config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'quotations/:id/pdf', to: 'quotations#pdf', as: :pdf
  get 'quotations/:id/pdf.pdf', to: 'quotations#pdf', as: :to_pdf
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities, only: %i[index new create destroy]
  resources :products, only: %i[index new create destroy]
  resources :elements, only: %i[index new create destroy]
  resources :customers
  resources :quotations do
    resources :rooms, only: %i[new create]
  end

  resources :rooms, only: %i[new create] do
    resources :tasks, only: %i[new create]
  end

  resources :rooms, only: %i[destroy]
  resources :tasks, only: %i[destroy]
end

app/models/element.rb
class Element < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  belongs_to :user
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def index
    @elements = Element.where(user_id: current_user.id)
  end

  def new
    @element = Element.new
  end

  def create
    @element = Element.new(element_params)
    @element.user_id = current_user.id
    if @element.save
      redirect_to elements_path
    else
      render :new
    end
  end

  def destroy
    @element = Element.find(params[:id])
    @element.destroy
    redirect_to elements_path, notice: 'Element was successfully destroyed.'
  end

  private

  def element_params
    params.require(:element).permit(:name, :user_id)
  end
end

app/views/elements/index.html.erb
<div class="action-container">
<h1>Elements</h1>
<%#  test %>

<div class="btn-new-item">
  <%= link_to 'nouvelle element', new_element_path, class: 'btn-flat'%>
</div>

<% @elements.each do |element|%>
  <ul>
    <li><%= element.name %>  <%= link_to element_path(element), method: :delete, data: { confirm: "Are you sure?" } do %>
                                <i class="fa-solid fa-trash" style=" font-size: 20px; color: red; margin-left: 16px"></i>
                              <% end %> </li>
  </ul>
<% end %>
</div>

app/views/elements/new.html.erb
<%= simple_form_for [@element] do |f| %>

  <%= f.input :name%>
  <%= f.button :submit, class: 'btn btn-gradient'%>
<% end %>