config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'quotations/:id/pdf', to: 'quotations#pdf', as: :pdf
  get 'quotations/:id/pdf.pdf', to: 'quotations#pdf', as: :to_pdf
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities, only: %i[index new create destroy]
  resources :products, only: %i[index new create destroy]
  resources :elements, only: %i[index new create destroy]
  resources :customers
  resources :quotations do
    resources :rooms, only: %i[new create]
  end

  resources :rooms, only: %i[new create] do
    resources :tasks, only: %i[new create]
  end

  resources :rooms, only: %i[destroy]
  resources :tasks, only: %i[destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn.create.vista.com/api/media/small/150716174/stock-vector-bank-building-icon-in-flat" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Clients", customers_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Devis", quotations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link",data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
           <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://cantoin.com/new/wp-content/uploads/2021/01/icone-avatar-personnage-homme-travailleur-construit-mur_51635-1793-e1612262367971.jpg" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to 'Actions', activities_path, class: 'dropdown-item' %>
              <%= link_to 'Elements', elements_path, class: 'dropdown-item' %>
              <%= link_to 'Produits', products_path, class: 'dropdown-item' %>

            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>