config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'quotations/:id/pdf', to: 'quotations#pdf', as: :pdf
  get 'quotations/:id/pdf.pdf', to: 'quotations#pdf', as: :to_pdf
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities, only: %i[index new create destroy]
  resources :products, only: %i[index new create destroy]
  resources :elements, only: %i[index new create destroy]
  resources :customers
  resources :quotations do
    resources :rooms, only: %i[new create]
  end

  resources :rooms, only: %i[new create] do
    resources :tasks, only: %i[new create]
  end

  resources :rooms, only: %i[destroy]
  resources :tasks, only: %i[destroy]
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :quotations
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.where(user_id: current_user.id)
  end

  def show
    @customer = Customer.find(params[:id])
    @marker =
      {
        lat: @customer.latitude,
        lng: @customer.longitude
      }
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.user = current_user
    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path, notice: 'Customer was successfully destroyed.'
  end

  private

  def customer_params
    params.require(:customer).permit(:email, :first_name, :last_name, :address, :address_2, :phone)
  end
end

app/views/customers/edit.html.erb
<h1>Editer client</h1>
<%= simple_form_for [@customer] do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name%>
  <%= f.input :email%>
  <%= f.input :phone%>
  <%= f.input :address%>
  <label for="">si besoin</label>
  <%= f.input :address_2%>

  <%= f.button :submit, class: 'btn btn-gradient'%>
<% end %>

app/views/customers/index.html.erb
<h1 style="margin:16px;">Liste clients</h1>

<div class="new-customer">
  <%= link_to 'ajouter un client', new_customer_path, class: 'btn-flat' %></div>
</div>

<ul>
  <% @customers.each do |customer| %>
    <%= link_to customer_path(customer) do %>
      <li style="margin-top: 12px;"><%= customer.first_name.capitalize%> <%= customer.last_name.capitalize%>
      <%= link_to edit_customer_path(customer)  do %>
                                <i class="fa-solid fa-pen" style=" font-size: 20px; color: green; margin-left: 16px"></i>
                              <% end %>
      <%= link_to customer_path(customer), method: :delete, data: { confirm: "Are you sure?" } do %>
                                <i class="fa-solid fa-trash" style=" font-size: 20px; color: red; margin-left: 16px"></i>
                              <% end %> </li>
    <% end %>
  <% end %>
</ul>

app/views/customers/new.html.erb
<h1>Nouveau client</h1>
<%= simple_form_for [@customer] do |f| %>
  <%= f.input :first_name, label: 'Prenom' %>
  <%= f.input :last_name, label: 'Nom'%>
  <%= f.input :email%>
  <%= f.input :phone%>
  <%= f.input :address, label: 'Adresse'%>
  <label for="">si besoin</label>
  <%= f.input :address_2, label: 'Adresse 2'%>

  <%= f.button :submit, class: 'btn btn-gradient'%>
<% end %>

app/views/customers/show.html.erb
<div class="customer-container">

<%= link_to new_quotation_path do %>
  <h1 style="text-align:center;"><%= @customer.first_name.capitalize%>  <%= @customer.last_name.capitalize %> </h1>

<% end %>


<p><%= @customer.email %></p>
<p><a href="tel://+33<%= @customer.phone[1..-1] %>"><%= @customer.phone.insert(2, ' ').insert(5, ' ').insert(8, ' ').insert(11, ' ')  %><a></p>
<p><%= @customer.address%></p>

<% if @customer.address_2 %>
<p><%= @customer.address_2%></p>
<% end %>


<div class="client-devis">
  <% if @customer.quotations.empty? %>
  <p>Aucun devis pour l'instant </p>
  <% end %>
  <% @customer.quotations.each do |quotation|%>
    <ul>
      <%= link_to quotation_path(quotation) do%>
        <li>devis n°<%= quotation.number %> <%= quotation.date %></li>
      <% end %>
    </ul>
  <% end %>
</div>
</div>

<div class="map-container">
  <div style="width: 88%; height: 240px; filter: drop-shadow(-2px -2px 4px rgba(0, 0, 0, 0.25)) drop-shadow(2px 2px 4px rgba(0, 0, 0, 0.25));"
        data-controller="mapbox"
        data-mapbox-marker-value="<%= @marker.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>