config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'quotations/:id/pdf', to: 'quotations#pdf', as: :pdf
  get 'quotations/:id/pdf.pdf', to: 'quotations#pdf', as: :to_pdf
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities, only: %i[index new create destroy]
  resources :products, only: %i[index new create destroy]
  resources :elements, only: %i[index new create destroy]
  resources :customers
  resources :quotations do
    resources :rooms, only: %i[new create]
  end

  resources :rooms, only: %i[new create] do
    resources :tasks, only: %i[new create]
  end

  resources :rooms, only: %i[destroy]
  resources :tasks, only: %i[destroy]
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  has_many :rooms, dependent: :destroy
  has_many_attached :photos
  validates :number, presence: true, uniqueness: true
end

app/controllers/quotations_controller.rb
require "open-uri"

class QuotationsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = <<~SQL
        customers.first_name ILIKE :query
        OR customers.last_name ILIKE :query
        OR customers.address ILIKE :query
      SQL
      @quotations = Quotation.joins(:customer).where(sql_query, query: "%#{params[:query]}%", user_id: current_user.id)
    else
      @quotations = Quotation.where(user_id: current_user.id)
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'list.html', locals: { quotations: @quotations } }
    end
  end

  def show
    @quotation = Quotation.find(params[:id])
  end

  def pdf
    file1 = URI.open('https://i.ibb.co/pZdsJy5/Capture-d-e-cran-2022-07-18-a-17-56-38.png')
    file2 = URI.open('https://i.ibb.co/kSVrSzb/Capture-d-e-cran-2022-07-19-a-13-59-30.png')
    photos = [file1, file2]
    @quotation = Quotation.find(params[:id])
    unless @quotation.photos.attached?
      photos.each_with_index do |photo, index|
        @quotation.photos.attach(io: photo, filename: "#{index}.png", content_type: 'image/png')
      end
      @quotation.save
    end
    html_string = render_to_string(
      {
        template: 'quotations/pdf.html.erb',
        locals: { id: params[:id] }
      }
    )
    pdf = Grover.new(html_string, format: 'A4', display_url: "http://localhost:3000").to_pdf
    respond_to do |format|
      format.html
      format.pdf do
        send_data(pdf, disposition: 'inline', filename: "DEVIS_ID_#{params[:id]}", type: 'application/pdf')
      end
    end
  end


  def new
    @customers = Customer.where(user_id: current_user.id)
    @quotation = Quotation.new
  end

  def create
    @quotation = Quotation.new(quotation_params)
    @quotation.user = current_user
    if @quotation.save
      redirect_to @quotation
    else
      render :new
    end
  end

  def edit
    @quotation = Quotation.find(params[:id])
  end

  def update
    @quotation = Quotation.find(params[:id])
    @quotation.update(quotation_params)
    redirect_to quotation_path(@quotation)
  end

  def destroy
    @quotation = Quotation.find(params[:id])
    @quotation.destroy
    redirect_to quotations_path, notice: 'Quotation was successfully destroyed.'
  end

  private

  def quotation_params
    params.require(:quotation).permit(:number, :date, :customer_id, :total_price, photo: [])
  end
end

app/views/quotations/_list.html.erb
<div data-refresh-list-target="list" class="quotations-container">

    <% @quotations.each do |quotation|%>
      <%= link_to quotation_path(quotation) do%>
          <div class="card text-white bg-dark mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Devis N°<%= quotation.number%></h5>
            <h6 class="card-subtitle mb-2 text-white"><%= quotation.customer.first_name.capitalize%> <%= quotation.customer.last_name.capitalize%></h6>
            <p class="card-text"><%= quotation.customer.address%></p>
            <p class="card-text"><%= quotation.date.strftime("%d/%m/%Y") %></p>

          </div>
        </div>
      <% end %>
    <% end %>

</div>

app/views/quotations/edit.html.erb
<h1>Editer devis</h1>
<%= simple_form_for [@customer,@quotation] do |f| %>
  <%= f.association :customer, label_method: lambda { |customer| "#{customer.first_name}  #{customer.last_name}" }%>
  <%= f.input :number %>
  <%= f.input :date %>
  <%= f.input :total_price%>
  <%= f.button :submit, class: 'btn btn-gradient'%>
<% end %>

app/views/quotations/index.html.erb
<div data-controller="refresh-list">
<h1 style="margin:16px;">Tous mes Devis</h1>

<div class="quotation-new">
  <%= link_to 'nouveau devis', new_quotation_path, class: 'btn-flat'%>
</div>

<div class="search-bar" >
    <%= form_tag quotations_path, method: :get, class: 'd-flex',  data: { refresh_list_target: 'form' }  do %>
      <%= text_field_tag :query,
        params[:query],
         data: {
          refresh_list_target: 'searchInput', action: "keyup->refresh-list#update"
                    },
        class: "form-control",
        placeholder: "chercher un devis"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
</div>




<%= render "list", quotations: @quotations %>
</div>

app/views/quotations/new.html.erb
<h1>Nouveau devis</h1>
<%= simple_form_for [@customer,@quotation] do |f| %>
  <%= f.association :customer, label_method: lambda { |customer| "#{customer.first_name}  #{customer.last_name}" }%>
  <label style="color: green;">Devis précédent: <strong><%= Quotation.where(user_id: current_user.id).last.number %></strong></label>
  <%= f.input :number, label: 'Numero du devis' %>
  <%= f.input :date %>
  <%= f.input :total_price%>
  <%= f.button :submit, class: 'btn btn-gradient'%>
<% end %>

app/views/quotations/pdf.html.erb
<div class="pdf-container">
<div class="banner-logo-martin">
  <%# <img src="https://i.ibb.co/pZdsJy5/Capture-d-e-cran-2022-07-18-a-17-56-38.png" alt="banner" class="logo-martin" > %>
  <%= cl_image_tag @quotation.photos[0].key, class:"logo-martin", :width => 860 %>
</div>
<div class="quotation-header">
  <p style="text-decoration: underline; margin-left: 16px;"><strong><%= @quotation.date.strftime("%d/%m/%Y") %></strong></p>
</div>


<div class="quotation-customer">
  <h3 style="text-align: end;"><strong style="text-decoration: underline;"><%= @quotation.customer.first_name.parameterize.upcase %> <%= @quotation.customer.last_name.parameterize.upcase %></strong> </h3>
</div>

<div class="quotation-customer">
  <p style="text-align: end;"><%= @quotation.customer.address.split(",")[0] ? @quotation.customer.address.split(",")[0].parameterize.upcase : @quotation.customer.address.parameterize.upcase %></p>
</div>

<div class="quotation-customer">
  <p style="text-align: end;"><%= @quotation.customer.address.split(",")[1].parameterize.upcase if @quotation.customer.address.split(",")[1] %></p>
</div>


<div>
  <h4 style="text-align:center;text-decoration: underline;"><strong>DEVIS</strong></h4>
  <h4 style="text-align:center; margin-bottom: 44px;text-decoration: underline;"><strong>N <%= @quotation.number %></strong></h4>
</div>

<div class="quotation-details">
  <h6>PREPARATION</h6>
  <ul>
    <li>MISE EN PLACE CHANTIER</li>
  </ul>
  <% @quotation.rooms.each do |room|%>
    <h6><%= room.name.upcase %></h6>
    <% room.tasks.each do |task|%>

    <ul>
      <li><%= task.activity.name.parameterize.upcase %> <%= "#{task.product.name.parameterize.upcase}" if task.product  %> <%= "#{task.element.name.parameterize.upcase}" if task.element %> <%= "#{task.number_of_items} UNITEE(S)" if task.number_of_items  %> <%= "#{task.m2} M2" if task.m2  %> <%= task.description.empty? ?  "" : "( #{task.description.parameterize.upcase } )"   %>  </li>
    </ul>

    <% end %>
  <% end %>
</div>

<div>
  <p style="text-align:center;">Prix forfaitaire :  <strong><%= @quotation.total_price %></strong> Euros</p>
  <p style="text-align:center;"><strong>TVA non applicable -Article 293 B du CGI</strong></p>

</div>

<div class="signature">
  <h5 style="text-align:center; margin: 68px;text-decoration: underline;"><strong>SIGNATURE</strong></h5>
</div>


<div class="banner-logo-martin">
  <%= cl_image_tag @quotation.photos[1].key, class:"logo-martin", :width => 860  %>
</div>


</div>






<% unless action_name == 'pdf.pdf'%>
<div class="devis-btn">

   <%= link_to to_pdf_path(@quotation) do %>
    <i class="fa-solid fa-check" style="font-size: 16px; color: #000000"></i>
   <% end %>
</div>

<% end %>

app/views/quotations/show.html.erb
<div class="room-collection">
  <% @quotation.rooms.each do |room| %>

    <%= link_to new_room_task_path(room), class:"button-34 green"  do %>
      <%= room.name %>
    <% end %>
  <% end %>

</div>
<div class="quotation-header">
  <h1>Devis N°<%= @quotation.number %></h1>
  <p><%= @quotation.date.strftime("%d/%m/%Y") %></p>
</div>

<%= link_to customer_path( @quotation.customer) do %>
<div class="customer-container">
  <h3><%= @quotation.customer.first_name.capitalize %> <%= @quotation.customer.last_name.capitalize %> </h3>
  <p><%= @quotation.customer.address %></p>
</div>
<% end %>

<div class="quotation-details">
  <h5>Details</h5>
  <ul>
    <li>Mise en place chantier</li>
  </ul>
  <% @quotation.rooms.each do |room|%>
    <h6><%= room.name.capitalize %> <%= link_to room_path(room), method: :delete, data: { confirm: "Are you sure?" } do %>
                                      <i class="fa-solid fa-trash" style=" font-size: 20px; color: red; margin-left: 16px"></i>
                                    <% end %></h6>
    <% room.tasks.each do |task|%>

    <ul>
      <li><%= task.activity.name.capitalize %> <%= "#{task.product.name}" if task.product  %> <%= "#{task.element.name}" if task.element %> <%= "#{task.number_of_items} unitée(s)" if task.number_of_items  %> <%= "#{task.m2} m2" if task.m2  %> <%= task.description.empty? ? "" : "( #{task.description.capitalize } )"  %> <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
                                <i class="fa-solid fa-trash" style=" font-size: 20px; color: black; margin-left: 16px"></i>
                              <% end %> </li>
    </ul>

    <% end %>
  <% end %>
</div>

<div class="quotation-total">
  <p style="text-align:center;">Prix forfaitaire :  <strong><%= @quotation.total_price %></strong> Euros</p>
</div>


<div class="devis-btn">
  <%= link_to "Ajouter piéces",  new_quotation_room_path(@quotation), class: 'button-34 gold' %>
  <%= link_to "Editer devis",  edit_quotation_path(@quotation), class: 'button-34 darker' %>
  <%= link_to "Exporter en pdf", pdf_path(@quotation), class: 'button-34 purple'%>
  <%= link_to "Supprimer",  quotation_path(@quotation), method: :delete, class: 'button-34 red', data: { confirm: "Are you sure?" } %>
</div>